// This file is auto-generated by @hey-api/openapi-ts

import {
    type Client,
    formDataBodySerializer,
    type Options as Options2,
    type TDataShape,
    urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
    AuthJwtLoginAuthJwtLoginPostData,
    AuthJwtLoginAuthJwtLoginPostErrors,
    AuthJwtLoginAuthJwtLoginPostResponses,
    AuthJwtLogoutAuthJwtLogoutPostData,
    AuthJwtLogoutAuthJwtLogoutPostErrors,
    AuthJwtLogoutAuthJwtLogoutPostResponses,
    DeleteFeedApiPostsDeleteDeleteData,
    DeleteFeedApiPostsDeleteDeleteErrors,
    DeleteFeedApiPostsDeleteDeleteResponses,
    GetFeedApiPostsFeedGetData,
    GetFeedApiPostsFeedGetErrors,
    GetFeedApiPostsFeedGetResponses,
    RegisterRegisterAuthRegisterPostData,
    RegisterRegisterAuthRegisterPostErrors,
    RegisterRegisterAuthRegisterPostResponses,
    ResetForgotPasswordAuthForgotPasswordPostData,
    ResetForgotPasswordAuthForgotPasswordPostErrors,
    ResetForgotPasswordAuthForgotPasswordPostResponses,
    ResetResetPasswordAuthResetPasswordPostData,
    ResetResetPasswordAuthResetPasswordPostErrors,
    ResetResetPasswordAuthResetPasswordPostResponses,
    UploadFileApiPostsUploadPostData,
    UploadFileApiPostsUploadPostErrors,
    UploadFileApiPostsUploadPostResponses,
    UsersCurrentUserAuthMeGetData,
    UsersCurrentUserAuthMeGetErrors,
    UsersCurrentUserAuthMeGetResponses,
    UsersDeleteUserAuthIdDeleteData,
    UsersDeleteUserAuthIdDeleteErrors,
    UsersDeleteUserAuthIdDeleteResponses,
    UsersPatchCurrentUserAuthMePatchData,
    UsersPatchCurrentUserAuthMePatchErrors,
    UsersPatchCurrentUserAuthMePatchResponses,
    UsersPatchUserAuthIdPatchData,
    UsersPatchUserAuthIdPatchErrors,
    UsersPatchUserAuthIdPatchResponses,
    UsersUserAuthIdGetData,
    UsersUserAuthIdGetErrors,
    UsersUserAuthIdGetResponses,
    VerifyRequestTokenAuthRequestVerifyTokenPostData,
    VerifyRequestTokenAuthRequestVerifyTokenPostErrors,
    VerifyRequestTokenAuthRequestVerifyTokenPostResponses,
    VerifyVerifyAuthVerifyPostData,
    VerifyVerifyAuthVerifyPostErrors,
    VerifyVerifyAuthVerifyPostResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload File
 */
export const uploadFileApiPostsUploadPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UploadFileApiPostsUploadPostData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UploadFileApiPostsUploadPostResponses,
        UploadFileApiPostsUploadPostErrors,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/posts/upload",
        ...options,
        headers: {
            "Content-Type": null,
            ...options.headers,
        },
    });

/**
 * Get Feed
 */
export const getFeedApiPostsFeedGet = <ThrowOnError extends boolean = false>(
    options: Options<GetFeedApiPostsFeedGetData, ThrowOnError>,
) =>
    (options.client ?? client).get<
        GetFeedApiPostsFeedGetResponses,
        GetFeedApiPostsFeedGetErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/posts/feed",
        ...options,
    });

/**
 * Delete Feed
 */
export const deleteFeedApiPostsDeleteDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteFeedApiPostsDeleteDeleteData, ThrowOnError>,
) =>
    (options.client ?? client).delete<
        DeleteFeedApiPostsDeleteDeleteResponses,
        DeleteFeedApiPostsDeleteDeleteErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/posts/delete",
        ...options,
    });

/**
 * Auth:Jwt.Login
 */
export const authJwtLoginAuthJwtLoginPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<AuthJwtLoginAuthJwtLoginPostData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        AuthJwtLoginAuthJwtLoginPostResponses,
        AuthJwtLoginAuthJwtLoginPostErrors,
        ThrowOnError
    >({
        ...urlSearchParamsBodySerializer,
        url: "/auth/jwt/login",
        ...options,
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            ...options.headers,
        },
    });

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogoutAuthJwtLogoutPost = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<AuthJwtLogoutAuthJwtLogoutPostData, ThrowOnError>,
) =>
    (options?.client ?? client).post<
        AuthJwtLogoutAuthJwtLogoutPostResponses,
        AuthJwtLogoutAuthJwtLogoutPostErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/jwt/logout",
        ...options,
    });

/**
 * Register:Register
 */
export const registerRegisterAuthRegisterPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<RegisterRegisterAuthRegisterPostData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        RegisterRegisterAuthRegisterPostResponses,
        RegisterRegisterAuthRegisterPostErrors,
        ThrowOnError
    >({
        url: "/auth/register",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Verify:Request-Token
 */
export const verifyRequestTokenAuthRequestVerifyTokenPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        VerifyRequestTokenAuthRequestVerifyTokenPostData,
        ThrowOnError
    >,
) =>
    (options.client ?? client).post<
        VerifyRequestTokenAuthRequestVerifyTokenPostResponses,
        VerifyRequestTokenAuthRequestVerifyTokenPostErrors,
        ThrowOnError
    >({
        url: "/auth/request-verify-token",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Verify:Verify
 */
export const verifyVerifyAuthVerifyPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<VerifyVerifyAuthVerifyPostData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        VerifyVerifyAuthVerifyPostResponses,
        VerifyVerifyAuthVerifyPostErrors,
        ThrowOnError
    >({
        url: "/auth/verify",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Reset:Forgot Password
 */
export const resetForgotPasswordAuthForgotPasswordPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        ResetForgotPasswordAuthForgotPasswordPostData,
        ThrowOnError
    >,
) =>
    (options.client ?? client).post<
        ResetForgotPasswordAuthForgotPasswordPostResponses,
        ResetForgotPasswordAuthForgotPasswordPostErrors,
        ThrowOnError
    >({
        url: "/auth/forgot-password",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Reset:Reset Password
 */
export const resetResetPasswordAuthResetPasswordPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<ResetResetPasswordAuthResetPasswordPostData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        ResetResetPasswordAuthResetPasswordPostResponses,
        ResetResetPasswordAuthResetPasswordPostErrors,
        ThrowOnError
    >({
        url: "/auth/reset-password",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Users:Current User
 */
export const usersCurrentUserAuthMeGet = <ThrowOnError extends boolean = false>(
    options?: Options<UsersCurrentUserAuthMeGetData, ThrowOnError>,
) =>
    (options?.client ?? client).get<
        UsersCurrentUserAuthMeGetResponses,
        UsersCurrentUserAuthMeGetErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/me",
        ...options,
    });

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserAuthMePatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UsersPatchCurrentUserAuthMePatchData, ThrowOnError>,
) =>
    (options.client ?? client).patch<
        UsersPatchCurrentUserAuthMePatchResponses,
        UsersPatchCurrentUserAuthMePatchErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/me",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Users:Delete User
 */
export const usersDeleteUserAuthIdDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UsersDeleteUserAuthIdDeleteData, ThrowOnError>,
) =>
    (options.client ?? client).delete<
        UsersDeleteUserAuthIdDeleteResponses,
        UsersDeleteUserAuthIdDeleteErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/{id}",
        ...options,
    });

/**
 * Users:User
 */
export const usersUserAuthIdGet = <ThrowOnError extends boolean = false>(
    options: Options<UsersUserAuthIdGetData, ThrowOnError>,
) =>
    (options.client ?? client).get<
        UsersUserAuthIdGetResponses,
        UsersUserAuthIdGetErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/{id}",
        ...options,
    });

/**
 * Users:Patch User
 */
export const usersPatchUserAuthIdPatch = <ThrowOnError extends boolean = false>(
    options: Options<UsersPatchUserAuthIdPatchData, ThrowOnError>,
) =>
    (options.client ?? client).patch<
        UsersPatchUserAuthIdPatchResponses,
        UsersPatchUserAuthIdPatchErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/auth/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
