// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth:jwt.login
 */
export type BodyAuthJwtLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_reset:forgot_password
 */
export type BodyResetForgotPassword = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_reset:reset_password
 */
export type BodyResetResetPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * Caption
     */
    caption?: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_verify:request-token
 */
export type BodyVerifyRequestToken = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_verify:verify
 */
export type BodyVerifyVerify = {
    /**
     * Token
     */
    token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PostModel
 */
export type PostModel = {
    /**
     * Caption
     */
    caption: string;
    /**
     * Url
     */
    url: string;
    /**
     * File Type
     */
    file_type: string;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: unknown;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/api/posts/upload';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: PostModel;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type GetFeedData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Limit
         */
        limit: number;
    };
    url: '/api/posts/feed';
};

export type GetFeedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFeedError = GetFeedErrors[keyof GetFeedErrors];

export type GetFeedResponses = {
    /**
     * Response Get Feed
     *
     * Successful Response
     */
    200: Array<PostModel>;
};

export type GetFeedResponse = GetFeedResponses[keyof GetFeedResponses];

export type DeleteFeedData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/posts/delete';
};

export type DeleteFeedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFeedError = DeleteFeedErrors[keyof DeleteFeedErrors];

export type DeleteFeedResponses = {
    /**
     * Successful Response
     */
    200: PostModel;
};

export type DeleteFeedResponse = DeleteFeedResponses[keyof DeleteFeedResponses];

export type AuthJwtLoginData = {
    body: BodyAuthJwtLogin;
    path?: never;
    query?: never;
    url: '/auth/jwt/login';
};

export type AuthJwtLoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthJwtLoginResponse = AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/jwt/logout';
};

export type AuthJwtLogoutErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthJwtLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterRegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterError = RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterResponse = RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type VerifyRequestTokenData = {
    body: BodyVerifyRequestToken;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type VerifyRequestTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRequestTokenError = VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyData = {
    body: BodyVerifyVerify;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyVerifyErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyVerifyResponse = VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type ResetForgotPasswordData = {
    body: BodyResetForgotPassword;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ResetForgotPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetForgotPasswordError = ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordData = {
    body: BodyResetResetPassword;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetResetPasswordError = ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type UsersCurrentUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserResponse = UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type UsersPatchCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserError = UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserResponse = UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersPatchUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserError = UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserResponse = UsersPatchUserResponses[keyof UsersPatchUserResponses];
