// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth_jwt_login_auth_jwt_login_post
 */
export type BodyAuthJwtLoginAuthJwtLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_reset_forgot_password_auth_forgot_password_post
 */
export type BodyResetForgotPasswordAuthForgotPasswordPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_reset_reset_password_auth_reset_password_post
 */
export type BodyResetResetPasswordAuthResetPasswordPost = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_upload_file_api_posts_upload_post
 */
export type BodyUploadFileApiPostsUploadPost = {
    /**
     * Caption
     */
    caption?: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_verify_request_token_auth_request_verify_token_post
 */
export type BodyVerifyRequestTokenAuthRequestVerifyTokenPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_verify_verify_auth_verify_post
 */
export type BodyVerifyVerifyAuthVerifyPost = {
    /**
     * Token
     */
    token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PostModel
 */
export type PostModel = {
    /**
     * Caption
     */
    caption: string;
    /**
     * Url
     */
    url: string;
    /**
     * File Type
     */
    file_type: string;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: unknown;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UploadFileApiPostsUploadPostData = {
    body: BodyUploadFileApiPostsUploadPost;
    path?: never;
    query?: never;
    url: '/api/posts/upload';
};

export type UploadFileApiPostsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiPostsUploadPostError = UploadFileApiPostsUploadPostErrors[keyof UploadFileApiPostsUploadPostErrors];

export type UploadFileApiPostsUploadPostResponses = {
    /**
     * Successful Response
     */
    200: PostModel;
};

export type UploadFileApiPostsUploadPostResponse = UploadFileApiPostsUploadPostResponses[keyof UploadFileApiPostsUploadPostResponses];

export type GetFeedApiPostsFeedGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Limit
         */
        limit: number;
    };
    url: '/api/posts/feed';
};

export type GetFeedApiPostsFeedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFeedApiPostsFeedGetError = GetFeedApiPostsFeedGetErrors[keyof GetFeedApiPostsFeedGetErrors];

export type GetFeedApiPostsFeedGetResponses = {
    /**
     * Response Get Feed Api Posts Feed Get
     *
     * Successful Response
     */
    200: Array<PostModel>;
};

export type GetFeedApiPostsFeedGetResponse = GetFeedApiPostsFeedGetResponses[keyof GetFeedApiPostsFeedGetResponses];

export type DeleteFeedApiPostsDeleteDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/api/posts/delete';
};

export type DeleteFeedApiPostsDeleteDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFeedApiPostsDeleteDeleteError = DeleteFeedApiPostsDeleteDeleteErrors[keyof DeleteFeedApiPostsDeleteDeleteErrors];

export type DeleteFeedApiPostsDeleteDeleteResponses = {
    /**
     * Successful Response
     */
    200: PostModel;
};

export type DeleteFeedApiPostsDeleteDeleteResponse = DeleteFeedApiPostsDeleteDeleteResponses[keyof DeleteFeedApiPostsDeleteDeleteResponses];

export type AuthJwtLoginAuthJwtLoginPostData = {
    body: BodyAuthJwtLoginAuthJwtLoginPost;
    path?: never;
    query?: never;
    url: '/auth/jwt/login';
};

export type AuthJwtLoginAuthJwtLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthJwtLoginAuthJwtLoginPostError = AuthJwtLoginAuthJwtLoginPostErrors[keyof AuthJwtLoginAuthJwtLoginPostErrors];

export type AuthJwtLoginAuthJwtLoginPostResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthJwtLoginAuthJwtLoginPostResponse = AuthJwtLoginAuthJwtLoginPostResponses[keyof AuthJwtLoginAuthJwtLoginPostResponses];

export type AuthJwtLogoutAuthJwtLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/jwt/logout';
};

export type AuthJwtLogoutAuthJwtLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthJwtLogoutAuthJwtLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterRegisterAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterRegisterAuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterAuthRegisterPostError = RegisterRegisterAuthRegisterPostErrors[keyof RegisterRegisterAuthRegisterPostErrors];

export type RegisterRegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterAuthRegisterPostResponse = RegisterRegisterAuthRegisterPostResponses[keyof RegisterRegisterAuthRegisterPostResponses];

export type VerifyRequestTokenAuthRequestVerifyTokenPostData = {
    body: BodyVerifyRequestTokenAuthRequestVerifyTokenPost;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostError = VerifyRequestTokenAuthRequestVerifyTokenPostErrors[keyof VerifyRequestTokenAuthRequestVerifyTokenPostErrors];

export type VerifyRequestTokenAuthRequestVerifyTokenPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyAuthVerifyPostData = {
    body: BodyVerifyVerifyAuthVerifyPost;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyVerifyAuthVerifyPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyVerifyAuthVerifyPostError = VerifyVerifyAuthVerifyPostErrors[keyof VerifyVerifyAuthVerifyPostErrors];

export type VerifyVerifyAuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyVerifyAuthVerifyPostResponse = VerifyVerifyAuthVerifyPostResponses[keyof VerifyVerifyAuthVerifyPostResponses];

export type ResetForgotPasswordAuthForgotPasswordPostData = {
    body: BodyResetForgotPasswordAuthForgotPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ResetForgotPasswordAuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetForgotPasswordAuthForgotPasswordPostError = ResetForgotPasswordAuthForgotPasswordPostErrors[keyof ResetForgotPasswordAuthForgotPasswordPostErrors];

export type ResetForgotPasswordAuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordAuthResetPasswordPostData = {
    body: BodyResetResetPasswordAuthResetPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetResetPasswordAuthResetPasswordPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetResetPasswordAuthResetPasswordPostError = ResetResetPasswordAuthResetPasswordPostErrors[keyof ResetResetPasswordAuthResetPasswordPostErrors];

export type ResetResetPasswordAuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersCurrentUserAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type UsersCurrentUserAuthMeGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserAuthMeGetResponse = UsersCurrentUserAuthMeGetResponses[keyof UsersCurrentUserAuthMeGetResponses];

export type UsersPatchCurrentUserAuthMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type UsersPatchCurrentUserAuthMePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserAuthMePatchError = UsersPatchCurrentUserAuthMePatchErrors[keyof UsersPatchCurrentUserAuthMePatchErrors];

export type UsersPatchCurrentUserAuthMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserAuthMePatchResponse = UsersPatchCurrentUserAuthMePatchResponses[keyof UsersPatchCurrentUserAuthMePatchResponses];

export type UsersDeleteUserAuthIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersDeleteUserAuthIdDeleteErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserAuthIdDeleteError = UsersDeleteUserAuthIdDeleteErrors[keyof UsersDeleteUserAuthIdDeleteErrors];

export type UsersDeleteUserAuthIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserAuthIdDeleteResponse = UsersDeleteUserAuthIdDeleteResponses[keyof UsersDeleteUserAuthIdDeleteResponses];

export type UsersUserAuthIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersUserAuthIdGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserAuthIdGetError = UsersUserAuthIdGetErrors[keyof UsersUserAuthIdGetErrors];

export type UsersUserAuthIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserAuthIdGetResponse = UsersUserAuthIdGetResponses[keyof UsersUserAuthIdGetResponses];

export type UsersPatchUserAuthIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/auth/{id}';
};

export type UsersPatchUserAuthIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserAuthIdPatchError = UsersPatchUserAuthIdPatchErrors[keyof UsersPatchUserAuthIdPatchErrors];

export type UsersPatchUserAuthIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserAuthIdPatchResponse = UsersPatchUserAuthIdPatchResponses[keyof UsersPatchUserAuthIdPatchResponses];
